ALTER TABLE users
    ADD COLUMN name       VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN email      VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
